adminRummet/Controllers/AdministracionController.cs
using Microsoft.AspNetCore.Mvc;

namespace adminRummet.Controllers
{
    public class AdministracionController : Controller
    {
       public IActionResult NuevaPropiedad()
        {
            return View(); 
        }

        public IActionResult LeadBrokerTab()
        {
            return View();
        }
        public IActionResult Brokers()
        {
            return View();
        }

        public IActionResult UsuariosTab()
        {
            return View();
        }

        public IActionResult PropiedadesTab()
        {
            return View();
        }
        public IActionResult DetallesPropiedad()
        {
            return View();
        }
        public  IActionResult DetallePropiedadRenta()
        {
            return View();
        }
        public IActionResult DetallesPropiedadNoPublicada()
        {
            return View();
        }

        public IActionResult DetallesPropiedadNoPublicadaPropietario()
        {
            return View();
        }

        public IActionResult DetallesPropiedadPublicadaPropietario()
        {
            return View();
        }
        public IActionResult DetallesPropiedadProcesoPropietario()
        {
            return View();
        }
        public IActionResult DetallesPropiedadNoPublicadaRenta()
        {
            return View();
        }
        public IActionResult DetallesPropiedadProceso()
        {
            return View();
        }
        public IActionResult EdicionUsuarioBroker()
        {
            return View();
        }
        public IActionResult TabMesaControl()
        {
            return View();
        }
        public IActionResult TabContactCenter()
        {
            return View();
        }
        public IActionResult DetallePropiedadProcesoRenta()
        {
            return View();
        }

        public IActionResult TableroBroker()
        {
            return View();
        }
        public IActionResult Propietario()
        {
            return View();
        }

        public IActionResult DatosPropietario()
        {
            return View();
        }

        public IActionResult EditConfigPlanes()
        {
            return View();
        }
        public IActionResult EdicionUsuario()
        {
            return View();
        }
        public IActionResult NuevoUsuario()
        {
            return View();
        }
        public IActionResult EdicionUsuarioM()
        {
            return View();
        }
        public IActionResult EdicionUsuarioMBroker()
        {
            return View();
        }
    }
}

adminRummet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto_administracion</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" />
    <script src="https://kit.fontawesome.com/e43b4d35fb.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/StyleLeadBroker.css">
    <link rel="icon" type="image/png" sizes="16x16" href="~/img/imagen-logo/logo_oficial.png">
    <link rel="stylesheet" href="~/css/main.css">

   
</head>
<body id="body">
    <header class="d-flex">
        <div class="icon__menu me-4 ms-3">
            <i class="fas fa-bars" id="btn_open"></i>
        </div>

        <div class=" d-inline-flex col-lg-10">
            <a class=" ms-3" style="color:#023D82;" asp-controller="Administracion" asp-action="PropiedadesTab">
                <h6 class="my-2 size-letter-menu">Propiedades</h6>
            </a>
            <a class=" ms-3" style="color:#023D82;" asp-controller="Administracion" asp-action="Brokers">
                <h6 class="my-2 size-letter-menu">Brokers</h6>
            </a>
            <a href="" class="ms-4" style="color:#023D82;">
                <h6 class="my-2 size-letter-menu">Informes</h6>
            </a>
        </div>
        <div class="col-lg-1 ">

            <a href="" class=" home-user">
                <img src="./img/persona1.jpg" alt=""
                     class="back-image-header img-fluid m-1 my-2">
            </a>
        </div>

    </header>

    <div class="menu__side shadow" id="side_menu">
        <a class="nav-link" asp-controller="Administracion" asp-action="TabContactCenter">
        <div class="name__page">
            <i class="fa-solid fa-house " title="home"></i>
            <h6>Home</h6>
        </div>
        </a>

        <div class="options__menu">

            <a class="selected" asp-controller="Administracion" asp-action="UsuariosTab">
                <div class="option">
                    <i class="fa-solid fa-user" title="user"></i>
                    <h6>Usuarios</h6>
                </div>
            </a>

            <a href="#">
                <div class="option">
                    <i class="fa-solid fa-gear" title="Configuración"></i>
                    <h6>Configuración</h6>
                </div>
            </a>

            <a class=" option" asp-controller="Administracion" asp-action="EditConfigPlanes">
                <div class="option">
                    <i class="fa-solid fa-cart-shopping" title="Planes"></i>
                    <h6>Planes</h6>
                </div>
            </a>

            <a href="#">
                <div class="option">
                    <i class="fa-solid fa-box-archive" title="Catalogo"></i>
                    <h6>Catalagos</h6>
                </div>
            </a>

            <a href="#">
                <div class="option">
                    <i class="fa-solid fa-gear" title="Configuración"></i>
                    <h6>Permisos</h6>
                </div>
            </a>

            <a href="#">
                <div class="option">
                    <i class="fa-solid fa-file-lines" title="Documentos"></i>
                    <h6>Documentos</h6>
                </div>
            </a>

            <a href="#">
                <div class="option">
                    <i class="fa-solid fa-headset" title="Nosotros"></i>
                    <h6>Soporte</h6>
                </div>
            </a>

            <a href="#">
                <div class="option">
                    <i class="fa-solid fa-door-open" title="Salir"></i>
                    <h6>Salir</h6>
                </div>
            </a>

        </div>

    </div>



    
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
   

    
    <script src="~/js/script.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/main.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="~/js/locales-all.js"></script>
   
</body>
</html>

adminRummet/Views/Shared/_NavDetallesPropiedad.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto_administracion</title>
    <link rel="icon" type="image/png" sizes="16x16" href="~/img/imagen-logo/logo_oficial.png">
    <link rel="stylesheet" href="~/css/main.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/styleDetallePropiedad.css">
    <script src="https://kit.fontawesome.com/e43b4d35fb.js" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.3/main.min.js"></script>
     <title>Detalle Propiedad</title>
</head>
<body id="body">
   
        <header class="d-flex">
            <div class="icon__menu me-4 ms-3">
                <i class="fas fa-bars" id="btn_open"></i>
            </div>

            <div class=" d-inline-flex col-lg-10">
            <a class=" ms-3" style="color:#023D82;" asp-controller="Administracion" asp-action="PropiedadesTab">
                    <h6 class="my-2 size-letter-menu">Propiedades</h6>
                </a>
            <a class=" ms-3" style="color:#023D82;" asp-controller="Administracion" asp-action="Brokers">
                    <h6 class="my-2 size-letter-menu">Brokers</h6>
                </a>
                <a href="" class="ms-4" style="color:#023D82;">
                    <h6 class="my-2 size-letter-menu">Informes</h6>
                </a>
            </div>
            <div class="col-lg-1 ">

                <a href="" class=" home-user">
                    <img src="./img/persona1.jpg" alt=""
                         class="back-image-header img-fluid m-1 shadow my-2">
                </a>
            </div>

        </header>

        <div class="menu__side" id="side_menu">
             <a class="" asp-controller="Administracion" asp-action="TabMesaControl">
            <div class="name__page">
                <i class="fa-solid fa-house " title="home"></i>
                <h6>Home</h6>
            </div>
            </a>

            <div class="options__menu">

            <a class="selected" asp-controller="Administracion" asp-action="UsuariosTab">
                    <div class="option">
                        <i class="fa-solid fa-user" title="user"></i>
                        <h6>Usuarios</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-gear" title="Configuración"></i>
                        <h6>Configuración</h6>
                    </div>
                </a>

            <a class=" option" asp-controller="Administracion" asp-action="EditConfigPlanes">
                    <div class="option">
                        <i class="fa-solid fa-cart-shopping" title="Planes"></i>
                        <h6>Planes</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-box-archive" title="Catalogo"></i>
                        <h6>Catalagos</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-gear" title="Configuración"></i>
                        <h6>Permisos</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-file-lines" title="Documentos"></i>
                        <h6>Documentos</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-headset" title="Nosotros"></i>
                        <h6>Soporte</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-door-open" title="Salir"></i>
                        <h6>Salir</h6>
                    </div>
                </a>

            </div>

        </div>








        <main role="main" class="pb-3">
            @RenderBody()
        </main>



        <!--Scripts-->

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"
                integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <script src="~/js/script.js"></script>
        <script src="~/js/script-visualizadores.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
        @await RenderSectionAsync("Scripts", required: false)
 
</body>
</html>

adminRummet/Views/Shared/_NavEditConfigPlanes.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <link rel="icon" type="image/png" sizes="16x16" href="~/img/imagen-logo/logo_oficial.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/styles_edit_config_planes.css">

    <link rel="stylesheet" href="~/css/style_usuarios.css">


    <script src="https://kit.fontawesome.com/e43b4d35fb.js" crossorigin="anonymous"></script>
    <title>Usuarios</title>
</head>

<body id="body">
    <div class="area">
        <ul class="circles">
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>

        <header class="d-flex">
            <div class="icon__menu me-4 ms-3">
                <i class="fas fa-bars" id="btn_open"></i>
            </div>

            <div class=" d-inline-flex col-lg-10">
                <a class=" ms-3" style="color:#023D82;" asp-controller="Administracion" asp-action="PropiedadesTab">
                    <h6 class="my-2 size-letter-menu">Propiedades</h6>
                </a>
                <a class=" ms-3" style="color:#023D82;" asp-controller="Administracion" asp-action="Brokers">
                    <h6 class="my-2 size-letter-menu">Brokers</h6>
                </a>
                <a href="" class="ms-4" style="color:#023D82;">
                    <h6 class="my-2 size-letter-menu">Informes</h6>
                </a>
            </div>
            <div class="col-lg-1 ">

                <a href="" class=" home-user">
                    <img src="./img/persona1.jpg" alt=""
                         class="back-image-header img-fluid m-1 my-2">
                </a>
            </div>

        </header>

        <div class="menu__side" id="side_menu">
            <a class="" asp-controller="Administracion" asp-action="TabMesaControl">
                <div class="name__page">
                    <i class="fa-solid fa-house " title="home"></i>
                    <h6>Home</h6>
                </div>
            </a>
            <div class="options__menu">

                <a class="" asp-controller="Administracion" asp-action="TabMesaControl">
                    <div class="option">
                        <i class="fa-solid fa-user" title="user"></i>
                        <h6>Usuarios</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-gear" title="Configuración"></i>
                        <h6>Configuración</h6>
                    </div>
                </a>

                <a class=" option" asp-controller="Administracion" asp-action="EditConfigPlanes">
                    <div class="option">
                        <i class="fa-solid fa-cart-shopping" title="Planes"></i>
                        <h6>Planes</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-box-archive" title="Catalogo"></i>
                        <h6>Catalagos</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-gear" title="Configuración"></i>
                        <h6>Permisos</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-file-lines" title="Documentos"></i>
                        <h6>Documentos</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-headset" title="Nosotros"></i>
                        <h6>Soporte</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-door-open" title="Salir"></i>
                        <h6>Salir</h6>
                    </div>
                </a>

            </div>

        </div>



    </div>

    <main role="main" class="pb-3">
        @RenderBody()
    </main>



</body>

</html>

adminRummet/Views/Shared/_NavFormNuevoUsuario.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

     
    <!--estas son las hojas de estilo de la barra de navegacion de Edicion Usuario -->

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" />
    <link href="~/assets/css/material-bootstrap-wizard.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/style_form_nuevo_usuario.css">
    



    <link rel="icon" type="image/png" sizes="16x16" href="~/img/imagen-logo/logo_oficial.png">
    <script src="https://kit.fontawesome.com/e43b4d35fb.js" crossorigin="anonymous"></script>

    <title>Formulario nuevo usuario</title>
</head>


<main role="main" class="pb-3">
    @RenderBody()
</main>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
<script src="~/js/script-step.js"></script>
<script src="~/js/script.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="~/assets/js/jquery-2.2.4.min.js" type="text/javascript"></script>



@await RenderSectionAsync("Scripts", required: false)

<!--   Core JS Files   -->

<script src="~/assets/js/bootstrap.min.js" type="text/javascript"></script>
<script src="~/assets/js/jquery.bootstrap.js" type="text/javascript"></script>


<!--  Plugin for the Wizard -->
<script src="~/assets/js/material-bootstrap-wizard.js"></script>

<!--  More information about jquery.validate here: http://jqueryvalidation.org/	 -->
<script src="~/assets/js/jquery.validate.min.js"></script>


</html>

adminRummet/Views/Shared/_NavMbd.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto_administracion</title>
    <link rel="icon" type="image/png" sizes="16x16" href="~/img/imagen-logo/logo_oficial.png">
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/style_tablero_brokers.css">
    <script src="https://kit.fontawesome.com/e43b4d35fb.js" crossorigin="anonymous"></script>
</head>
<body id="body">
    <div class="area">

        <ul class="circles">
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    <header class="d-flex">
        <div class="icon__menu me-4 ms-3">
            <i class="fas fa-bars" id="btn_open"></i>
        </div>

        <div class=" d-inline-flex col-lg-10">
                <a class=" ms-3" style="color:#023D82;" asp-controller="Administracion" asp-action="PropiedadesTab">
                <h6 class="my-2 size-letter-menu">Propiedades</h6>
            </a>
                <a class=" ms-3" style="color:#023D82;" asp-controller="Administracion" asp-action="Brokers">
                <h6 class="my-2 size-letter-menu">Brokers</h6>
            </a>
                <a href="" class="ms-4" style="color:#023D82;">
                <h6 class="my-2 size-letter-menu">Informes</h6>
            </a>
        </div>
        <div class="col-lg-1 ">

            <a href="" class=" home-user">
                <img src="./img/persona1.jpg" alt=""
                     class="back-image-header img-fluid m-1 shadow my-2">
            </a>
        </div>

    </header>

        <div class="menu__side" id="side_menu">
             <a class=" style-vermas" asp-controller="Administracion" asp-action="TabMesaControl">
            <div class="name__page">
                <i class="fa-solid fa-house " title="home"></i>
                <h6>Home</h6>
            </div>
            </a>

            <div class="options__menu">

                <a class="selected" asp-controller="Administracion" asp-action="UsuariosTab">
                    <div class="option">
                        <i class="fa-solid fa-user" title="user"></i>
                        <h6>Usuarios</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-gear" title="Configuración"></i>
                        <h6>Configuración</h6>
                    </div>
                </a>

               <a class=" option" asp-controller="Administracion" asp-action="EditConfigPlanes">
                    <div class="option">
                        <i class="fa-solid fa-cart-shopping" title="Planes"></i>
                        <h6>Planes</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-box-archive" title="Catalogo"></i>
                        <h6>Catalagos</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-gear" title="Configuración"></i>
                        <h6>Permisos</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-file-lines" title="Documentos"></i>
                        <h6>Documentos</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-headset" title="Nosotros"></i>
                        <h6>Soporte</h6>
                    </div>
                </a>

                <a href="#">
                    <div class="option">
                        <i class="fa-solid fa-door-open" title="Salir"></i>
                        <h6>Salir</h6>
                    </div>
                </a>

            </div>

        </div>

      

      





    <main role="main" class="pb-3">
        @RenderBody()
    </main>

   

    <!--Scripts-->
    <script>
        // Script para tab de tablero de brokers
        function openCity(evt, cityName) {
            var i, tabcontent, tablinks;
            tabcontent = document.getElementsByClassName("tabcontent");
            for (i = 0; i < tabcontent.length; i++) {
                tabcontent[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablinks");
            for (i = 0; i < tablinks.length; i++) {
                tablinks[i].className = tablinks[i].className.replace(" active", "");
            }
            document.getElementById(cityName).style.display = "block";
            evt.currentTarget.className += " active";
        }

        // Get the element with id="defaultOpen" and click on it
        document.getElementById("defaultOpen").click();
    </script>

    <script src="~/js/script.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.js"></script>
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    </div>
</body>
</html>

adminRummet/Views/Shared/_NavOnlyWizard.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto_administracion</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" />
    <link href="~/assets/css/material-bootstrap-wizard-2.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/style_nueva_propiedad.css">
    <link rel="icon" type="image/png" sizes="16x16" href="~/img/imagen-logo/logo_oficial.png">
    <script src="https://kit.fontawesome.com/e43b4d35fb.js" crossorigin="anonymous"></script>

</head>
<body id="body">
    <header class="d-flex">
        <div class="icon__menu me-4 ms-3">
            <i class="fas fa-bars" id="btn_open"></i>
        </div>

        <div class=" d-inline-flex col-lg-10">
            <a class=" ms-3" style="color:#023D82;" asp-controller="Administracion" asp-action="PropiedadesTab">
                <h6 class="my-2 size-letter-menu">Propiedades</h6>
            </a>
            <a class=" ms-3" style="color:#023D82;" asp-controller="Administracion" asp-action="Brokers">
                <h6 class="my-2 size-letter-menu">Brokers</h6>
            </a>
            <a href="" class="ms-4" style="color:#023D82;">
                <h6 class="my-2 size-letter-menu">Informes</h6>
            </a>
        </div>
        <div class="col-lg-1 ">

            <a href="" class=" home-user">
                <img src="./img/persona1.jpg" alt=""
                     class="back-image-header img-fluid m-1 my-2">
            </a>
        </div>

    </header>

    <div class="menu__side" id="side_menu">
        <a class=" style-vermas" asp-controller="Administracion" asp-action="TabMesaControl">
            <div class="name__page">
                <i class="fa-solid fa-house " title="home"></i>
                <h6>Home</h6>
            </div>
        </a>
        <div class="options__menu">

            <a class="selected" asp-controller="Administracion" asp-action="UsuariosTab">
                <div class="option">
                    <i class="fa-solid fa-user" title="user"></i>
                    <h6>Usuarios</h6>
                </div>
            </a>

            <a href="#">
                <div class="option">
                    <i class="fa-solid fa-gear" title="Configuración"></i>
                    <h6>Configuración</h6>
                </div>
            </a>

         <a class=" option" asp-controller="Administracion" asp-action="EditConfigPlanes">
                <div class="option">
                    <i class="fa-solid fa-cart-shopping" title="Planes"></i>
                    <h6>Planes</h6>
                </div>
            </a>

            <a href="#">
                <div class="option">
                    <i class="fa-solid fa-box-archive" title="Catalogo"></i>
                    <h6>Catalagos</h6>
                </div>
            </a>

            <a href="#">
                <div class="option">
                    <i class="fa-solid fa-gear" title="Configuración"></i>
                    <h6>Permisos</h6>
                </div>
            </a>

            <a href="#">
                <div class="option">
                    <i class="fa-solid fa-file-lines" title="Documentos"></i>
                    <h6>Documentos</h6>
                </div>
            </a>

            <a href="#">
                <div class="option">
                    <i class="fa-solid fa-headset" title="Nosotros"></i>
                    <h6>Soporte</h6>
                </div>
            </a>

            <a href="#">
                <div class="option">
                    <i class="fa-solid fa-door-open" title="Salir"></i>
                    <h6>Salir</h6>
                </div>
            </a>

        </div>

    </div>




    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="~/js/script-step.js"></script>
    <script src="~/js/script.js"></script>
    <script src="~/assets/js/jquery-2.2.4.min.js" type="text/javascript"></script>
    <script src="~/js/invoice.js"></script>
    
   
   
    @await RenderSectionAsync("Scripts", required: false)

    <!--   Core JS Files   -->
    
    <script src="~/assets/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/assets/js/jquery.bootstrap.js" type="text/javascript"></script>


    <!--  Plugin for the Wizard -->
    <script src="~/assets/js/material-bootstrap-wizard.js"></script>

    <!--  More information about jquery.validate here: http://jqueryvalidation.org/	 -->
    <script src="~/assets/js/jquery.validate.min.js"></script>

  
  
</body>
</html>